#include <stdio.h>
#include <stdlib.h>

#define PAGESIZE 3

int main() 
{
    int n;
    printf("Enter the size of page table: ");   //Enter the size of page table
    scanf("%d", &n);

    printf("Enter the page table values:\n");    //Enter the values of page table
    int pagetable[n];
    for (int i = 0; i < n; i++) 
        scanf("%d", &pagetable[i]);
    

    printf("  Page Table\n");
    printf("Page No | Frame No\n");              //Display the page table
    printf("-----------------\n");
    for (int i = 0; i < n; i++) 
    {
        printf("   %d    |   %d\n", i, pagetable[i]);
        printf("-----------------\n");
    }

    int log;
    printf("Enter the logical address: "); //Enter the logical addres generated by CPU
    scanf("%d", &log);

    int pageno = log / PAGESIZE;      //Calculate page number
    if (pageno >= n) 
    {
        printf("Page limit exceeded\n");
        return 0;
    }

    int offset = log % PAGESIZE;      //Calculate the offset
    if (offset >= PAGESIZE)
    {
        printf("Limit exceeded\n");
        return 0;
    }

    int frameno = pagetable[pageno];    //Calculate the frame number
    int phys = (frameno * PAGESIZE) + offset;  //Calculate the Physical address

    printf("Page No: %d\n", pageno);
    printf("Offset: %d\n", offset);
    printf("Frame No: %d\n", frameno);
    printf("Physical Address: %d\n", phys);

    return 0;
}
